# Generated by Django 6.0.4 on 2026-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_linkedin_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], default='manual', help_text='AI-sent vs human-sent message', max_length=10, verbose_name='Message Source'),
        ),
    ]
