# Generated by Django 6.0.4 on 2026-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='unanswered_follow_up_count',
            field=models.IntegerField(default=0, help_text='Number of consecutive AI follow-ups without a reply'),
        ),
    ]
