# Generated by Django 6.0.6 on 2026-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the next nudge/first-message is due (unified check_messages handler)', null=True),
        ),
    ]
