# Generated by Django 6.0.6 on 2026-07-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_deal_next_follow_up_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='agent_objective',
            field=models.TextField(blank=True, default='', help_text='Last agent objective description'),
        ),
        migrations.AddField(
            model_name='deal',
            name='agent_objective_category',
            field=models.CharField(blank=True, default='', help_text='Last agent objective category', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='agent_reasoning_summary',
            field=models.TextField(blank=True, default='', help_text='Last agent reasoning summary'),
        ),
        migrations.AddField(
            model_name='deal',
            name='agent_user_states',
            field=models.JSONField(blank=True, default=None, help_text='Last agent user states (RecipientState, ConversationState, RelationshipState, BusinessState)', null=True),
        ),
    ]
