# Generated by Django 6.0.6 on 2026-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_add_agent_decision_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
