# Generated by Django 6.0.6 on 2026-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_deal_opportunity_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='agent_action_reason',
            field=models.TextField(blank=True, default='', help_text='Last agent action reason'),
        ),
    ]
