# Generated by Django 6.0.6 on 2026-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0010_drop_legacy_pending_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('check_messages', 'Check Messages')], max_length=20),
        ),
    ]
