# Generated by Django 6.1.4 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_add_check_messages_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='conversation_ai_model',
            field=models.CharField(blank=True, default='gpt-5-mini', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-5-nano', max_length=200),
        ),
    ]
